import { useCallback, useEffect, useMemo, useState } from 'react';
import { RefreshCw, ShieldCheck, Store } from 'lucide-react';
import { Link } from 'react-router-dom';
import { getAuthorizedSellerCatalogGaps,getAuthorizedSellerNetwork,getAuthorizedSellerReadiness,getWave1Activation,type AuthorizedSellerNetworkResponse,type Wave1ActivationResponse } from '../lib/api';
import { StatusBadge } from '../components/ui/StatusBadge';

export function AuthorizedSellers(){
  const token=sessionStorage.getItem('cornerops-console-token')||'';const [network,setNetwork]=useState<AuthorizedSellerNetworkResponse>();const [wave1,setWave1]=useState<Wave1ActivationResponse>();const [ready,setReady]=useState(new Map<string,boolean>());const [gaps,setGaps]=useState(new Set<string>());const [error,setError]=useState('');const [loading,setLoading]=useState(true);
  const load=useCallback(async()=>{setLoading(true);try{const [next,readiness,catalogGaps,wave]=await Promise.all([getAuthorizedSellerNetwork(token),getAuthorizedSellerReadiness(token),getAuthorizedSellerCatalogGaps(token),getWave1Activation(token)]);setNetwork(next);setWave1(wave);setReady(new Map(readiness.sellers.map((item)=>[item.canonicalKey,item.catalogReady])));setGaps(new Set(catalogGaps.gaps.map((item)=>item.canonicalKey)));setError('');}catch(reason){setError(reason instanceof Error?reason.message:'Authorized Seller Network unavailable.');}finally{setLoading(false);}},[token]);
  useEffect(()=>{void load();},[load]);
  const totals=useMemo(()=>({profiles:network?.sellers.length||0,catalogReady:network?.sellers.filter((seller)=>(ready.get(seller.canonicalKey)??(seller.catalogProductCount>0))).length||0,products:wave1?.sellers.reduce((sum,seller)=>sum+seller.productCount,0)??network?.sellers.reduce((sum,seller)=>sum+seller.catalogProductCount,0)??0,gaps:gaps.size}),[network,wave1,ready,gaps]);
  return <div className="control-tower-page"><header className="ct-title"><div><span className="eyebrow">SupplyGraph v1.14 · authorized verified scope</span><h1>Authorized Sellers</h1><p>Founder-attested seller profiles, public catalog evidence and operational inventory. No market-completeness or best-supplier claim.</p></div><button onClick={()=>void load()} disabled={loading}><RefreshCw className={loading?'spin':''} size={14}/>Refresh</button></header>
    <div className="ct-safety-grid">{[['Authorized profiles',totals.profiles],['Catalog-ready',totals.catalogReady],['Verified catalog products',totals.products],['Catalog gaps',totals.gaps]].map(([label,value])=><div className="ct-safety-item" key={label}><small>{label}</small><strong>{value}</strong></div>)}</div>
    <section className="panel ct-panel"><div className="panel-heading"><div><span className="eyebrow">Safety boundary</span><h2>Internal assessment only</h2></div><StatusBadge tone="green">WRITES BLOCKED</StatusBadge></div><div className="ct-meta"><span>External contact <strong>blocked</strong></span><span>Purchasing <strong>blocked</strong></span><span>Quote generation <strong>blocked</strong></span><span>Market comparison <strong>not performed</strong></span></div></section>
    {error&&<div className="ct-locked"><ShieldCheck size={20}/><div><strong>Seller network locked safely</strong><p>{error}</p></div></div>}
    {wave1&&<section className="panel ct-panel"><div className="panel-heading"><div><span className="eyebrow">Wave 1 activation</span><h2>Official catalog progress</h2></div><StatusBadge tone="green">{wave1.sellers.filter((seller)=>seller.catalogReady).length} / 14 READY</StatusBadge></div><div className="table-wrap"><table className="ct-table"><thead><tr><th>Order</th><th>Seller</th><th>Source</th><th>Products</th><th>Media</th><th>Inventory</th></tr></thead><tbody>{wave1.sellers.map((seller)=><tr key={seller.canonicalKey}><td>{seller.activationOrder}</td><td><Link to={`/authorized-sellers/${encodeURIComponent(seller.sellerId||seller.canonicalKey)}`}>{seller.canonicalName}</Link></td><td>{seller.sourceVerificationStatus}</td><td>{seller.productCount}</td><td>{seller.imageCount}</td><td>{seller.inventoryProductCount}</td></tr>)}</tbody></table></div></section>}
    {network&&<section className="panel ct-panel"><div className="panel-heading"><div><span className="eyebrow">Registry checksum pinned</span><h2>Seller profiles</h2></div><StatusBadge tone="neutral">{network.sellers.length} SELLERS</StatusBadge></div><div className="table-wrap"><table className="ct-table"><thead><tr><th>Seller</th><th>Authorization</th><th>Source</th><th>Catalog</th><th>Pipeline</th></tr></thead><tbody>{network.sellers.map((seller)=><tr key={seller.canonicalKey}><td className="cell-primary"><Store size={14}/> {seller.canonicalName}</td><td><StatusBadge tone="green">{seller.authorizationStatus}</StatusBadge></td><td>{seller.sourceMode}</td><td><StatusBadge tone={(ready.get(seller.canonicalKey)??(seller.catalogProductCount>0))?'green':'amber'}>{seller.catalogProductCount||'profile only'}</StatusBadge></td><td>{[seller.pipelinePriority,seller.pipelineWave].filter(Boolean).join(' · ')||'not assigned'}</td></tr>)}</tbody></table></div></section>}
    <section className="panel ct-panel"><div className="panel-heading"><div><span className="eyebrow">Deferred capability</span><h2>Basket optimization</h2></div><StatusBadge tone="neutral">NOT IMPLEMENTED</StatusBadge></div><p>Split-sourcing may be indicated by coverage evidence, but supplier combinations and landed-cost optimization remain deferred to v1.15.</p></section>
  </div>;
}
