const express = require('express');
const controller = require('../controllers/dataController');

const router = express.Router();

router.get('/orders/requiring-action', controller.listOrdersRequiringAction);
router.get('/orders/manual-payments', controller.listManualPaymentOrders);
router.post('/orders/:id/status-change-request', controller.requestOrderStatusChange);
router.post('/orders/:id/manual-payment-mark-paid-request', controller.requestManualPaymentMarkPaid);
router.get('/orders', controller.listOrders);
router.get('/mock/orders', controller.listOrders);
router.get('/orders/:orderNumber', controller.getOrder);
router.get('/products/search', controller.listProducts);
router.get('/products', controller.listProducts);
router.get('/mock/products', controller.listProducts);
router.get('/products/:sku', controller.getProduct);
router.get('/leads/follow-up', controller.listLeadsFollowUp);
router.get('/leads', controller.listLeads);
router.get('/mock/leads', controller.listLeads);
router.get('/leads/:id', controller.getLead);
router.post('/leads/:id/status-change-request', controller.requestLeadStatusChange);
router.patch('/leads/:id', controller.updateLead);
router.get('/quotes/follow-up', controller.listQuotesFollowUp);
router.get('/quotes', controller.listQuotes);
router.get('/quotes/:id', controller.getQuote);
router.get('/github/issues', controller.listGitHubIssues);
router.post('/github/issues/draft', controller.createGitHubIssueDraft);
router.post('/github/issues', controller.createGitHubIssue);
router.get('/github/issues/:number', controller.getGitHubIssue);
router.get('/github/pull-requests', controller.listGitHubPullRequests);
router.get('/github/pull-requests/:number', controller.getGitHubPullRequest);
router.get('/github/workflow-runs', controller.listGitHubWorkflowRuns);
router.get('/github/workflow-runs/:id', controller.getGitHubWorkflowRun);
router.get('/github/repository', controller.getGitHubRepository);
router.post('/github/webhook', controller.receiveGitHubWebhook);
router.get('/audit-logs', controller.listAuditLogs);
router.get('/approvals', controller.listApprovals);
router.post('/approvals', controller.createApproval);
router.post('/approvals/:id/approve', controller.approveApproval);
router.post('/approvals/:id/reject', controller.rejectApproval);
router.get('/data-health', controller.getDataHealth);
router.get('/openclaw-ecosystem/services', controller.listOpenClawEcosystemServices);
router.get('/openclaw-ecosystem/skills', controller.listOpenClawSkills);
router.post('/openclaw-ecosystem/skills/review', controller.reviewOpenClawSkill);
router.post('/openclaw-ecosystem/skills/:id/approve', controller.approveOpenClawSkill);
router.post('/openclaw-ecosystem/skills/:id/disable', controller.disableOpenClawSkill);
router.post('/openclaw-ecosystem/crabox/run-suite', controller.runCraboxSuite);
router.post('/openclaw-ecosystem/lobster/workflows/dry-run', controller.dryRunLobsterWorkflow);
router.get('/conversations', controller.listConversations);
router.get('/conversations/:id/messages', controller.listConversationMessages);
router.get('/conversations/:id', controller.getConversation);
router.get('/worker-runs', controller.listWorkerRuns);
router.get('/dashboard', controller.getDashboard);
router.get('/workers', controller.listWorkers);
router.patch('/workers/:id', controller.updateWorker);
router.get('/events', controller.listEvents);
router.get('/handoffs', controller.listHandoffs);
router.patch('/handoffs/:id', controller.updateHandoff);
router.get('/integrations', controller.listIntegrations);
router.patch('/integrations/:id', controller.updateIntegration);
router.get('/settings', controller.getSettings);
router.put('/settings', controller.updateSettings);

module.exports = router;
