const controller = require('../controllers/dataController');
const { policyRouter, requirePolicy } = require('../middleware/appAuth');

// Every route here requires a workspace session. GET needs any active
// membership; each mutation states its execution policy.
const router = policyRouter();
const internalWrite = requirePolicy('internal_write');
const sensitiveConfig = requirePolicy('sensitive_config');
const externalAction = requirePolicy('external_action');

router.get('/orders/requiring-action', controller.listOrdersRequiringAction);
router.get('/orders/manual-payments', controller.listManualPaymentOrders);
router.post('/orders/:id/status-change-request', internalWrite, controller.requestOrderStatusChange);
router.post('/orders/:id/manual-payment-mark-paid-request', internalWrite, controller.requestManualPaymentMarkPaid);
router.get('/orders', controller.listOrders);
router.get('/orders/:orderNumber', controller.getOrder);
router.get('/products/search', controller.listProducts);
router.get('/products', controller.listProducts);
router.get('/products/:sku', controller.getProduct);
router.get('/leads/follow-up', controller.listLeadsFollowUp);
router.get('/leads', controller.listLeads);
router.get('/leads/:id', controller.getLead);
router.post('/leads/:id/status-change-request', internalWrite, controller.requestLeadStatusChange);
router.patch('/leads/:id', internalWrite, controller.updateLead);
router.get('/quotes/follow-up', controller.listQuotesFollowUp);
router.get('/quotes', controller.listQuotes);
router.get('/quotes/:id', controller.getQuote);
router.get('/github/issues', controller.listGitHubIssues);
router.post('/github/issues/draft', internalWrite, controller.createGitHubIssueDraft);
router.post('/github/issues', externalAction, controller.createGitHubIssue);
router.get('/github/issues/:number', controller.getGitHubIssue);
router.get('/github/pull-requests', controller.listGitHubPullRequests);
router.get('/github/pull-requests/:number', controller.getGitHubPullRequest);
router.get('/github/workflow-runs', controller.listGitHubWorkflowRuns);
router.get('/github/workflow-runs/:id', controller.getGitHubWorkflowRun);
router.get('/github/repository', controller.getGitHubRepository);
router.get('/audit-logs', controller.listAuditLogs);
router.get('/approvals', controller.listApprovals);
router.post('/approvals', sensitiveConfig, controller.createApproval);
router.post('/approvals/:id/approve', sensitiveConfig, controller.approveApproval);
router.post('/approvals/:id/reject', sensitiveConfig, controller.rejectApproval);
router.get('/data-health', controller.getDataHealth);
router.get('/openclaw-ecosystem/services', controller.listOpenClawEcosystemServices);
router.get('/openclaw-ecosystem/skills', controller.listOpenClawSkills);
router.post('/openclaw-ecosystem/skills/review', sensitiveConfig, controller.reviewOpenClawSkill);
router.post('/openclaw-ecosystem/skills/:id/approve', sensitiveConfig, controller.approveOpenClawSkill);
router.post('/openclaw-ecosystem/skills/:id/disable', sensitiveConfig, controller.disableOpenClawSkill);
router.post('/openclaw-ecosystem/crabox/run-suite', sensitiveConfig, controller.runCraboxSuite);
router.post('/openclaw-ecosystem/lobster/workflows/dry-run', sensitiveConfig, controller.dryRunLobsterWorkflow);
router.get('/conversations', controller.listConversations);
router.get('/conversations/:id/messages', controller.listConversationMessages);
router.get('/conversations/:id', controller.getConversation);
router.get('/worker-runs', controller.listWorkerRuns);
router.get('/dashboard', controller.getDashboard);
router.get('/workers', controller.listWorkers);
router.patch('/workers/:id', sensitiveConfig, controller.updateWorker);
router.get('/events', controller.listEvents);
router.get('/handoffs', controller.listHandoffs);
router.patch('/handoffs/:id', internalWrite, controller.updateHandoff);
router.get('/integrations', controller.listIntegrations);
router.patch('/integrations/:id', sensitiveConfig, controller.updateIntegration);
router.get('/settings', controller.getSettings);
router.put('/settings', sensitiveConfig, controller.updateSettings);

module.exports = router;
