const {SellerMediaImportService,mimeFromBytes}=require('../src/core/supplygraph');
const png=Buffer.from([0x89,0x50,0x4e,0x47,0x0d,0x0a,0x1a,0x0a,1,2,3]);
const response=(body,mime='image/png',url='https://seller.example/a.png')=>({ok:true,url,arrayBuffer:async()=>body,headers:{get:()=>mime}});
describe('seller managed media v1.14',()=>{
  test('accepts JPEG, PNG and WebP magic bytes',()=>{expect(mimeFromBytes(Buffer.from([0xff,0xd8,0xff]))).toBe('image/jpeg');expect(mimeFromBytes(png)).toBe('image/png');expect(mimeFromBytes(Buffer.from('RIFF0000WEBP'))).toBe('image/webp');});
  test('rejects HTML, MIME mismatch and oversized payload',()=>{const service=new SellerMediaImportService();expect(()=>service.validate(Buffer.from('<html>'),'text/html')).toThrow();expect(()=>service.validate(png,'image/jpeg')).toThrow();expect(()=>service.validate(Buffer.alloc(5*1024*1024+1),'image/png')).toThrow();});
  test('imports one official asset and records managed evidence without external action',async()=>{const queries=[];const client={query:jest.fn(async(sql)=>{queries.push(sql);return{rows:[{id:'media-1'}]};})};const store={table:(name)=>`cornerops_internal.${name}`,withTransaction:async(fn)=>fn(client),appendAudit:jest.fn(async()=>({id:'audit'}))};const bucket={upload:jest.fn(async()=>({data:{},error:null})),getPublicUrl:jest.fn(()=>({data:{publicUrl:'https://cdn.example/asset.png'}}))};const service=new SellerMediaImportService({internalStore:store,storage:{from:()=>bucket},fetchImpl:async()=>response(png),config:{supplyGraphSellerMediaEnabled:true},allowedMediaHostnames:['seller.example']});const result=await service.importRow({id:'media-1',sellerId:'seller-1',supplierCatalogItemId:'product-1',sourceImageUrl:'https://seller.example/a.png',sourceHostname:'seller.example'});expect(result.mimeType).toBe('image/png');expect(bucket.upload).toHaveBeenCalledTimes(1);expect(store.appendAudit).toHaveBeenCalledTimes(1);expect(queries.join(' ')).not.toMatch(/delete|truncate/i);});
  test('rejects unapproved source hosts and redirects outside the allowlist',async()=>{const service=new SellerMediaImportService({internalStore:{withTransaction:jest.fn()},storage:{},fetchImpl:async()=>response(png,'image/png','https://evil.example/a.png'),config:{supplyGraphSellerMediaEnabled:true},allowedMediaHostnames:['seller.example']});await expect(service.importRow({sourceImageUrl:'https://unknown.example/a.png',sourceHostname:'unknown.example'})).rejects.toMatchObject({code:'SUPPLYGRAPH_MEDIA_SOURCE_DENIED'});await expect(service.importRow({sourceImageUrl:'https://seller.example/a.png',sourceHostname:'seller.example'})).rejects.toMatchObject({code:'SUPPLYGRAPH_MEDIA_SOURCE_DENIED'});});
  test('media import kill switch fails closed',async()=>{const service=new SellerMediaImportService({config:{supplyGraphSellerMediaEnabled:false}});await expect(service.importRow({sourceImageUrl:'https://seller.example/a.png',sourceHostname:'seller.example'})).rejects.toMatchObject({code:'SUPPLYGRAPH_SELLER_MEDIA_DISABLED'});});
});
