const { SupplierEvidenceResolver } = require('../src/core/supplygraph/SupplierEvidenceResolver');

const catalog={id:'item-1',supplierId:'supplier-1',sourceChecksum:'a'.repeat(64),sourceReference:'catalog'};
const legacy={id:'offer-1',unitPrice:10,currency:'AED',stockStatus:'unknown',observedAt:'2026-07-01T00:00:00Z',sourceChecksum:'a'.repeat(64),sourceType:'public_catalog_snapshot'};
const fact=(overrides={})=>({id:'fact-1',packageId:'pkg-1',supplierCatalogItemId:'item-1',factType:'stock_status',factKnown:true,factValue:{value:'in_stock'},observedAt:'2026-07-12T00:00:00Z',validUntil:'2026-08-01T00:00:00Z',sourceType:'supplier_call_summary',sourceChecksum:'b'.repeat(64),verificationStatus:'source_verified',evidenceScope:'production',packageStatus:'applied',...overrides});

describe('Supplier evidence resolver v1.12',()=>{
  const resolver=new SupplierEvidenceResolver({now:()=>Date.parse('2026-07-13T00:00:00Z')});
  test('human beats source, source beats legacy and provenance remains field-level',()=>{const result=resolver.resolve({catalogItem:catalog,legacyOffer:legacy,observations:[fact(),fact({id:'human',verificationStatus:'human_verified',factValue:{value:'limited'},sourceChecksum:'c'.repeat(64)})]});expect(result.fields.stock_status).toMatchObject({known:true,value:{value:'limited'},verificationStatus:'human_verified',factId:'human'});expect(result.fields.price.resolutionReason).toBe('legacy_baseline');});
  test('newer same trust wins and row ordering does not change watermark',()=>{const older=fact({id:'older',factValue:{value:'limited'},observedAt:'2026-07-10T00:00:00Z',sourceChecksum:'c'.repeat(64)});const newer=fact({id:'newer',observedAt:'2026-07-12T00:00:00Z',sourceChecksum:'d'.repeat(64)});const a=resolver.resolve({catalogItem:catalog,legacyOffer:legacy,observations:[older,newer]});const b=resolver.resolve({catalogItem:catalog,legacyOffer:legacy,observations:[newer,older]});expect(a.fields.stock_status.factId).toBe('newer');expect(a.watermark).toBe(b.watermark);});
  test('excludes expired, pending, rejected and acceptance-test facts',()=>{const observations=[fact({id:'expired',validUntil:'2026-07-12T00:00:00Z'}),fact({id:'pending',packageStatus:'pending_review'}),fact({id:'rejected',packageStatus:'rejected'}),fact({id:'acceptance',evidenceScope:'acceptance_test'})];const result=resolver.resolve({catalogItem:catalog,legacyOffer:legacy,observations});expect(result.fields.stock_status.value).toEqual({value:'unknown'});expect(result.affectedFactIds).not.toEqual(expect.arrayContaining(['expired','pending','rejected','acceptance']));});
  test('explicit unknown wins truthfully',()=>{const result=resolver.resolve({catalogItem:catalog,legacyOffer:legacy,observations:[fact({factKnown:false,factValue:null,verificationStatus:'human_verified'})]});expect(result.fields.stock_status).toMatchObject({known:false,value:null,resolutionReason:'explicit_unknown'});});
  test('detects equal-precedence and checksum conflicts without averaging',()=>{const equal=fact({id:'equal',factValue:{value:'limited'},sourceChecksum:'c'.repeat(64)});const first=resolver.resolve({catalogItem:catalog,legacyOffer:legacy,observations:[fact(),equal]});expect(first.fields.stock_status.conflict).toBe(true);const checksum=resolver.resolve({catalogItem:catalog,legacyOffer:legacy,observations:[fact(),fact({id:'other',factValue:{value:'limited'}})]});expect(checksum.conflicts[0].reason).toBe('same_checksum_different_payload');});
});
