const fs=require('fs');const path=require('path');
const file=path.join(__dirname,'../supabase/migrations/20260713070000_supplygraph_supplier_evidence_v112.sql');
const sql=fs.readFileSync(file,'utf8').toLowerCase();
describe('Supplier evidence migration v1.12',()=>{
  test('creates exactly the private evidence tables and no public objects',()=>{expect(sql).toContain('cornerops_internal.supplier_evidence_packages');expect(sql).toContain('cornerops_internal.supplier_fact_observations');expect(sql).toContain('cornerops_internal.supplier_evidence_applications');expect(sql).not.toMatch(/(?:create|alter|drop|truncate|insert into|update|delete from)\s+(?:table\s+)?public\./);});
  test('contains evidence constraints, foreign keys and focused indexes',()=>{for(const value of ['production','acceptance_test','pending_review','human_verified','price','stock_status','minimum_order','lead_time_days','shelf_life_days','temperature_zone'])expect(sql).toContain(`'${value}'`);expect(sql).toContain('unique(package_id,supplier_catalog_item_id,fact_type)');expect((sql.match(/create index if not exists/g)||[]).length).toBeGreaterThanOrEqual(14);});
  test('enforces append-only facts/applications and package no-delete controlled updates',()=>{expect(sql).toContain('supplier_fact_observations_append_only');expect(sql).toContain('supplier_evidence_applications_append_only');expect(sql).toContain('supplier_evidence_packages_guard');expect(sql).toContain("tg_op='delete'");expect(sql).toContain('immutable supplier evidence package fields cannot change');});
  test('grants exact runtime operations and revokes external roles',()=>{expect(sql).toContain('grant select,insert,update on cornerops_internal.supplier_evidence_packages to cornerops_internal_runtime');expect(sql).toContain('grant select,insert on cornerops_internal.supplier_fact_observations,cornerops_internal.supplier_evidence_applications to cornerops_internal_runtime');expect(sql).toContain('from public,anon,authenticated,service_role,cornerops_internal_runtime');expect(sql).not.toMatch(/grant\s+.*\s+to\s+(public|anon|authenticated|service_role)/);});
  test('does not rewrite legacy offers or historical matches',()=>{expect(sql).not.toMatch(/update\s+cornerops_internal\.supplier_offer_snapshots/);expect(sql).not.toMatch(/update\s+cornerops_internal\.sourcing_match_runs/);expect(sql).not.toContain('drop table');});
});
