const {
  IntermexCatalogSynchronizer, SupplyGraphMatchService, SupplyGraphMatchStore, SupplyGraphService,
  SupplyGraphStore, SupplierEvidenceResolver, SupplierEvidenceService, SupplierEvidenceStore, emptyState,
} = require('../src/core/supplygraph');
const { MemoryInternalOperationsStore } = require('../src/core/work-queue/MemoryInternalOperationsStore');

const config={supplyGraphEnabled:true,supplyGraphIntermexSyncEnabled:true,supplyGraphDemandIntakeEnabled:true,supplyGraphMatchingEnabled:true,supplyGraphSupplierEvidenceEnabled:true,supplyGraphEvidenceApplicationEnabled:true,supplyGraphEvidenceMaxFactsPerPackage:100,supplyGraphEvidenceExpiringSoonHours:72,supplyGraphMatchMaxCandidatesPerItem:5,supplyGraphObservationStaleAfterHours:168,supplyGraphIntermexSourceChecksum:'90f8585196507fbe3663586d5a902449828d67b52ca7db436dd06867c13f1934'};
const context={actorType:'founder',actorId:'founder-test',correlationId:'evidence-v112'};
const build=()=>{const state=emptyState();const workState={workItems:[],approvals:[],auditEvents:[]};const internalStore=new MemoryInternalOperationsStore({state:workState});const supplyGraphStore=new SupplyGraphStore({state,internalStore});const resolver=new SupplierEvidenceResolver({now:()=>Date.parse('2026-07-13T00:00:00Z')});const evidenceStore=new SupplierEvidenceStore({supplyGraphStore,internalStore});const evidenceService=new SupplierEvidenceService({store:evidenceStore,config,resolver});const matchStore=new SupplyGraphMatchStore({supplyGraphStore,internalStore,evidenceStore,evidenceResolver:resolver});const matchService=new SupplyGraphMatchService({matchStore,config});const service=new SupplyGraphService({store:supplyGraphStore,internalStore,config,matchStore,matchService,evidenceService,synchronizer:new IntermexCatalogSynchronizer()});return{state,workState,internalStore,evidenceService,service};};
const packageInput=(state,overrides={})=>{const item=state.catalogItems[0];const offer=state.offerSnapshots.find((x)=>x.supplierCatalogItemId===item.id);return{idempotencyKey:`pkg-${Math.random()}`,supplierId:item.supplierId,evidenceScope:'production',sourceType:'public_catalog_snapshot',sourceReference:item.sourceReference,sourceChecksum:item.sourceChecksum,observedAt:offer.observedAt,verificationStatus:'source_verified',facts:[{supplierCatalogItemId:item.id,factType:'price',value:{amount:Number(offer.unitPrice)},unit:offer.unitOfMeasure||item.unitOfMeasure||'catalog_item',currency:'AED'}],...overrides};};
const approve=async(internalStore,created)=>internalStore.decideApproval(created.package.approvalRequestId,'approved',{actorId:'founder-test',reason:'Reviewed internal evidence only.'});

describe('Supplier evidence workflow v1.12',()=>{
  test('creation is idempotent, creates one review/approval, preview is deterministic and apply is separate',async()=>{const{state,workState,internalStore,evidenceService,service}=build();await service.syncIntermex(context);const input=packageInput(state,{idempotencyKey:'no-change-package'});const created=await evidenceService.create(input,context);const repeated=await evidenceService.create(input,context);expect(created).toMatchObject({reused:false,package:{status:'pending_review'},approval:{status:'pending'}});expect(repeated.reused).toBe(true);expect(workState.workItems.filter((x)=>x.actionType==='review_supplier_evidence_package')).toHaveLength(1);expect(workState.approvals).toHaveLength(1);const preview1=await evidenceService.preview(created.package.id);const preview2=await evidenceService.preview(created.package.id);expect(preview1.previewFingerprint).toBe(preview2.previewFingerprint);expect(preview1.productionResolutionWouldChange).toBe(false);await expect(evidenceService.apply(created.package.id,{version:created.package.version,previewFingerprint:preview1.previewFingerprint},context)).rejects.toMatchObject({code:'SUPPLYGRAPH_EVIDENCE_APPROVAL_REQUIRED'});await approve(internalStore,created);const applied=await evidenceService.apply(created.package.id,{version:created.package.version,previewFingerprint:preview1.previewFingerprint},context);expect(applied).toMatchObject({application:{resultStatus:'no_material_change'},executed:false,externalActionsBlocked:true});await expect(evidenceService.apply(created.package.id,{version:created.package.version,previewFingerprint:preview1.previewFingerprint},context)).rejects.toMatchObject({code:'SUPPLYGRAPH_EVIDENCE_ALREADY_APPLIED'});expect(state.auditEvents.some((x)=>x.eventType==='supplier_evidence_package_applied')).toBe(true);});

  test('stale preview/version fail and cancellation is non-destructive',async()=>{const{state,evidenceService,service}=build();await service.syncIntermex(context);const created=await evidenceService.create(packageInput(state,{idempotencyKey:'cancel-package'}),context);await expect(evidenceService.apply(created.package.id,{version:999,previewFingerprint:'a'.repeat(64)},context)).rejects.toMatchObject({code:'SUPPLYGRAPH_EVIDENCE_VERSION_CONFLICT'});await expect(evidenceService.cancel(created.package.id,{version:created.package.version,reason:''},context)).rejects.toMatchObject({code:'SUPPLYGRAPH_EVIDENCE_REASON_REQUIRED'});const cancelled=await evidenceService.cancel(created.package.id,{version:created.package.version,reason:'Source withdrawn.'},context);expect(cancelled.status).toBe('cancelled');expect(state.factObservations.filter((x)=>x.packageId===created.package.id)).toHaveLength(1);});

  test('acceptance-test application persists but cannot affect resolver, fingerprint, confidence or rematch queue',async()=>{const{state,workState,internalStore,evidenceService,service}=build();await service.syncIntermex(context);const item=state.catalogItems[0];const demand=await service.createDemand({idempotencyKey:'acceptance-isolation-demand',customerSegment:'restaurant',emirate:'Dubai',requiredBy:'2026-08-15T00:00:00Z',requestedCurrency:'AED',sourceType:'test',items:[{itemKey:'known',productQuery:item.displayName,requestedQuantity:2,requestedUnit:'case',substitutesAllowed:false}]},context);const baseline=await service.matchDemand(demand.request.id,{version:1},context);const created=await evidenceService.create(packageInput(state,{idempotencyKey:'acceptance-only',evidenceScope:'acceptance_test',sourceType:'production_acceptance_test',verificationStatus:'unverified',sourceChecksum:'b'.repeat(64),observedAt:'2026-07-12T00:00:00Z',facts:[{supplierCatalogItemId:item.id,factType:'stock_status',value:{value:'in_stock'}},{supplierCatalogItemId:item.id,factType:'minimum_order',value:{quantity:2},unit:'case'},{supplierCatalogItemId:item.id,factType:'lead_time_days',value:{value:3}}]}),context);const preview=await evidenceService.preview(created.package.id,{includeAcceptanceTest:true});await approve(internalStore,created);const applied=await evidenceService.apply(created.package.id,{version:created.package.version,previewFingerprint:preview.previewFingerprint},context);expect(applied.application.resultStatus).toBe('acceptance_test_only');const repeated=await service.matchDemand(demand.request.id,{version:1},context);expect(repeated.reused).toBe(true);expect(repeated.matchRun.id).toBe(baseline.matchRun.id);expect(repeated.matchRun.overallConfidenceScore).toBe(baseline.matchRun.overallConfidenceScore);expect(workState.workItems.filter((x)=>x.sourceFlow==='supplygraph_rematch_after_evidence_flow')).toHaveLength(0);expect((await evidenceService.catalogEvidence(item.id)).observations).toHaveLength(0);});

  test('fresh verified stock, MOQ and lead time create a new run and increase confidence without changing Match Score',async()=>{const{state,internalStore,evidenceService,service}=build();await service.syncIntermex(context);const item=state.catalogItems[0];const demand=await service.createDemand({idempotencyKey:'uplift-demand',customerSegment:'restaurant',emirate:'Dubai',requiredBy:'2026-08-15T00:00:00Z',requestedCurrency:'AED',sourceType:'test',items:[{itemKey:'known',productQuery:item.displayName,requestedQuantity:2,requestedUnit:'case',substitutesAllowed:false}]},context);const baseline=await service.matchDemand(demand.request.id,{version:1},context);const created=await evidenceService.create(packageInput(state,{idempotencyKey:'uplift-package',sourceType:'internal_manual_verification',verificationStatus:'human_verified',reviewerReference:'founder-review-v112',sourceChecksum:'c'.repeat(64),observedAt:'2026-07-12T00:00:00Z',facts:[{supplierCatalogItemId:item.id,factType:'stock_status',value:{value:'in_stock'}},{supplierCatalogItemId:item.id,factType:'stock_quantity',value:{quantity:10},unit:'case'},{supplierCatalogItemId:item.id,factType:'minimum_order',value:{quantity:2},unit:'case'},{supplierCatalogItemId:item.id,factType:'lead_time_days',value:{value:3}}]}),context);const preview=await evidenceService.preview(created.package.id);await approve(internalStore,created);await evidenceService.apply(created.package.id,{version:created.package.version,previewFingerprint:preview.previewFingerprint},context);const uplifted=await service.matchDemand(demand.request.id,{version:1},context);expect(uplifted.reused).toBe(false);expect(uplifted.matchRun.inputFingerprint).not.toBe(baseline.matchRun.inputFingerprint);expect(uplifted.matchRun.overallMatchScore).toBe(baseline.matchRun.overallMatchScore);expect(Number(uplifted.matchRun.overallConfidenceScore)).toBeGreaterThan(Number(baseline.matchRun.overallConfidenceScore));expect(state.matchRuns.find((x)=>x.id===baseline.matchRun.id).overallConfidenceScore).toBe(baseline.matchRun.overallConfidenceScore);});

  test('conflicts and expiring evidence create deterministic internal review work only',async()=>{const{state,workState,evidenceService,service}=build();await service.syncIntermex(context);const item=state.catalogItems[0];const offer=state.offerSnapshots.find((x)=>x.supplierCatalogItemId===item.id);const conflict=await evidenceService.create(packageInput(state,{idempotencyKey:'conflict-work',facts:[{supplierCatalogItemId:item.id,factType:'price',value:{amount:Number(offer.unitPrice)+1},unit:offer.unitOfMeasure||item.unitOfMeasure||'catalog_item',currency:'AED'}]}),context);expect(conflict.operationalWorkQueue.items).toHaveLength(1);expect(workState.workItems.filter((x)=>x.actionType==='resolve_supplier_evidence_conflict')).toHaveLength(1);await evidenceService.create(packageInput(state,{idempotencyKey:'expiring-work',sourceChecksum:'d'.repeat(64),validUntil:new Date(Date.now()+3600000).toISOString()}),context);expect(workState.workItems.filter((x)=>x.actionType==='review_expiring_supplier_evidence')).toHaveLength(1);expect(workState.workItems.every((x)=>x.safePayload?.externalActionAllowed===false)).toBe(true);});

  test('kill switches block writes/application while existing reads and matching stay live',async()=>{const{state,evidenceService,service}=build();await service.syncIntermex(context);evidenceService.config.supplyGraphSupplierEvidenceEnabled=false;await expect(evidenceService.create(packageInput(state),context)).rejects.toMatchObject({statusCode:503});await expect(service.listCatalog({limit:1})).resolves.toHaveLength(1);evidenceService.config.supplyGraphSupplierEvidenceEnabled=true;evidenceService.config.supplyGraphEvidenceApplicationEnabled=false;const created=await evidenceService.create(packageInput(state,{idempotencyKey:'application-off'}),context);const preview=await evidenceService.preview(created.package.id);await expect(evidenceService.apply(created.package.id,{version:created.package.version,previewFingerprint:preview.previewFingerprint},context)).rejects.toMatchObject({code:'SUPPLYGRAPH_EVIDENCE_APPLICATION_DISABLED'});expect(created.package.status).toBe('pending_review');});
});
