const { createSupplyGraphError } = require('./supplyGraphTypes');
const { SupplierEvidenceValidator } = require('./SupplierEvidenceValidator');
const { SupplierEvidenceResolver } = require('./SupplierEvidenceResolver');
const { SupplierEvidencePreviewBuilder } = require('./SupplierEvidencePreviewBuilder');
const { EVIDENCE_MODEL_VERSION, EVIDENCE_RULESET_CHECKSUM, FACT_TYPES } = require('./supplierEvidenceRules');

class SupplierEvidenceService {
  constructor({ store, config = {}, validator, resolver, previewBuilder } = {}) {
    this.store=store;this.config=config;
    this.validator=validator||new SupplierEvidenceValidator({maxFacts:config.supplyGraphEvidenceMaxFactsPerPackage||100});
    this.resolver=resolver||new SupplierEvidenceResolver();
    this.previewBuilder=previewBuilder||new SupplierEvidencePreviewBuilder({resolver:this.resolver});
  }
  assertEnabled(capability='evidence'){if(!this.config.supplyGraphEnabled)throw createSupplyGraphError('SupplyGraph is disabled.','SUPPLYGRAPH_DISABLED',503);if(!this.config.supplyGraphSupplierEvidenceEnabled)throw createSupplyGraphError('Supplier evidence is disabled.','SUPPLYGRAPH_SUPPLIER_EVIDENCE_DISABLED',503);if(capability==='apply'&&!this.config.supplyGraphEvidenceApplicationEnabled)throw createSupplyGraphError('Evidence application is disabled.','SUPPLYGRAPH_EVIDENCE_APPLICATION_DISABLED',503);}
  operationalRecommendations(record,preview){
    const recommendations=[];const base={sourceType:'supplygraph_evidence',sourceId:record.id,safePayload:{internalOnly:true,executed:false,externalActionAllowed:false,supplierContactAllowed:false}};
    if(preview?.conflicts?.length)recommendations.push({...base,idempotencyKey:`supplygraph-evidence-conflict:${preview.previewFingerprint}`,sourceFlow:'supplygraph_supplier_evidence_conflict_flow',actionType:'resolve_supplier_evidence_conflict',title:'Resolve supplier evidence conflict',priority:'high',approvalRequired:false,evidence:{conditionActive:true,packageId:record.id,conflictCount:preview.conflicts.length,conflicts:preview.conflicts}});
    if(record.validUntil){const remaining=Date.parse(record.validUntil)-Date.now();const soon=(this.config.supplyGraphEvidenceExpiringSoonHours||72)*3600000;if(remaining<=0)recommendations.push({...base,idempotencyKey:`supplygraph-evidence-expired:${record.id}`,sourceFlow:'supplygraph_supplier_evidence_renewal_flow',actionType:'review_expired_supplier_evidence',title:'Review expired supplier evidence',priority:'high',approvalRequired:false,evidence:{conditionActive:true,packageId:record.id,validUntil:record.validUntil}});else if(remaining<=soon)recommendations.push({...base,idempotencyKey:`supplygraph-evidence-expiring:${record.id}:${record.validUntil}`,sourceFlow:'supplygraph_supplier_evidence_renewal_flow',actionType:'review_expiring_supplier_evidence',title:'Review expiring supplier evidence',priority:'medium',approvalRequired:false,evidence:{conditionActive:true,packageId:record.id,validUntil:record.validUntil}});}
    return recommendations;
  }
  async syncOperationalRecommendations(record,preview,context){const recommendations=this.operationalRecommendations(record,preview);if(!recommendations.length)return null;return this.store.internalStore.syncRecommendations(recommendations,{...context,sourceType:'supplygraph_evidence',sourceId:record.id});}
  async create(input,context){this.assertEnabled();const result=await this.store.create(this.validator.normalize(input,context.actorId),context);if(!result.reused){const preview=await this.preview(result.package.id,{includeAcceptanceTest:true});result.operationalWorkQueue=await this.syncOperationalRecommendations(result.package,preview,context);}return result;}
  async list(filters){return this.store.list(filters);}
  async get(id,options){return this.store.get(id,options);}
  async preview(id,{includeAcceptanceTest=false,client,packageOverride}={}){const inputs=await this.store.previewInputs(id,{includeAcceptanceTest,client});if(!inputs)return null;if(packageOverride)inputs.package={...inputs.package,...packageOverride};return this.previewBuilder.build({packageRecord:inputs.package,facts:inputs.facts,catalogById:inputs.catalogById,legacyOffersByCatalogId:inputs.legacyOffersByCatalogId,appliedObservationsByCatalogId:inputs.appliedObservationsByCatalogId});}
  async apply(id,command,context){this.assertEnabled('apply');const result=await this.store.apply(id,command,(client,record)=>this.preview(id,{includeAcceptanceTest:true,client,packageOverride:record}),context);if(result)result.operationalWorkQueue=await this.syncOperationalRecommendations(result.package,result.preview,context);return result;}
  async cancel(id,command,context){this.assertEnabled();return this.store.cancel(id,command,context);}
  async catalogEvidence(catalogItemId,{includeAcceptanceTest=false}={}){const observations=await this.store.appliedEvidenceForCatalog([catalogItemId],{includeAcceptanceTest});const inputs=await this.store.supplyGraphStore.getCatalogEvidenceInputs(catalogItemId);if(!inputs)return null;const resolved=this.resolver.resolve({catalogItem:inputs.catalogItem,legacyOffer:inputs.latestOffer,observations});return{catalogItemId,resolved,observations:observations.filter((fact)=>includeAcceptanceTest||fact.evidenceScope==='production'),acceptanceTestIncluded:includeAcceptanceTest};}
  async supplierStatus(supplierId){const catalog=[];for(let offset=0;;offset+=100){const page=await this.store.supplyGraphStore.listCatalog({supplierId,limit:100,offset});catalog.push(...page);if(page.length<100)break;}const facts=await this.store.appliedEvidenceForCatalog(catalog.map((item)=>item.id));const current=facts.filter((fact)=>!fact.validUntil||Date.parse(fact.validUntil)>Date.now());const coverage=Object.fromEntries(FACT_TYPES.map((type)=>[type,new Set(current.filter((fact)=>fact.factType===type&&fact.factKnown).map((fact)=>fact.supplierCatalogItemId)).size]));const matchReady=coverage.price>0&&coverage.stock_status>0&&coverage.minimum_order>0&&coverage.lead_time_days>0;return{supplierId,catalogItemCount:catalog.length,coverage,suppliersWithMatchReadyCommercialEvidence:matchReady?1:0,suppliersRequiringVerification:matchReady?0:1,evidenceModelVersion:EVIDENCE_MODEL_VERSION,evidenceRulesetChecksum:EVIDENCE_RULESET_CHECKSUM,multiSupplierComparisonReady:false,basketOptimizationStatus:'not_implemented'};}
  async conflicts(){const packages=await this.store.list({limit:100,includeAcceptanceTest:false});const output=[];for(const pkg of packages.filter((item)=>item.status==='pending_review')){const preview=await this.preview(pkg.id);if(preview?.conflicts.length)output.push({packageId:pkg.id,conflicts:preview.conflicts});}return output;}
  async expiring({hours}={}){const limitHours=Math.max(1,Math.min(Number(hours)||this.config.supplyGraphEvidenceExpiringSoonHours||72,720));const packages=await this.store.list({limit:100,includeAcceptanceTest:false});const threshold=Date.now()+limitHours*3600000;return packages.filter((pkg)=>pkg.validUntil&&Date.parse(pkg.validUntil)>Date.now()&&Date.parse(pkg.validUntil)<=threshold).map((pkg)=>({id:pkg.id,supplierId:pkg.supplierId,validUntil:pkg.validUntil,status:pkg.status}));}
  async status(){if(!this.config.supplyGraphSupplierEvidenceEnabled)return{status:'disabled',featureEnabled:false,applicationEnabled:Boolean(this.config.supplyGraphEvidenceApplicationEnabled),evidenceModelVersion:EVIDENCE_MODEL_VERSION,evidenceRulesetChecksum:EVIDENCE_RULESET_CHECKSUM,metrics:null,multiSupplierComparisonReady:false,basketOptimizationStatus:'not_implemented'};try{const metrics=await this.store.metrics();const [conflicts,expiring,suppliers]=await Promise.all([this.conflicts(),this.expiring({}),this.store.supplyGraphStore.listSuppliers({limit:100})]);const supplierStatuses=await Promise.all(suppliers.map((supplier)=>this.supplierStatus(supplier.id)));const coverage=Object.fromEntries(FACT_TYPES.map((type)=>[type,supplierStatuses.reduce((sum,item)=>sum+(item.coverage[type]||0),0)]));const enriched={...metrics,unresolvedConflicts:conflicts.reduce((sum,item)=>sum+item.conflicts.length,0),expiringFacts:expiring.length,staleFacts:metrics.expiredProductionFacts,coverage,supplierCountWithFreshPrice:supplierStatuses.filter((item)=>item.coverage.price>0).length,supplierCountWithFreshStock:supplierStatuses.filter((item)=>item.coverage.stock_status>0).length,supplierCountWithMOQ:supplierStatuses.filter((item)=>item.coverage.minimum_order>0).length,supplierCountWithLeadTime:supplierStatuses.filter((item)=>item.coverage.lead_time_days>0).length,suppliersWithMatchReadyCommercialEvidence:supplierStatuses.reduce((sum,item)=>sum+item.suppliersWithMatchReadyCommercialEvidence,0),suppliersRequiringVerification:supplierStatuses.reduce((sum,item)=>sum+item.suppliersRequiringVerification,0)};return{status:enriched.unresolvedConflicts?'conflict':enriched.staleFacts?'stale':'ready',featureEnabled:true,applicationEnabled:Boolean(this.config.supplyGraphEvidenceApplicationEnabled),evidenceModelVersion:EVIDENCE_MODEL_VERSION,evidenceRulesetChecksum:EVIDENCE_RULESET_CHECKSUM,metrics:enriched,multiSupplierComparisonReady:false,basketOptimizationStatus:'not_implemented'};}catch(error){return{status:'unavailable',featureEnabled:true,applicationEnabled:Boolean(this.config.supplyGraphEvidenceApplicationEnabled),evidenceModelVersion:EVIDENCE_MODEL_VERSION,evidenceRulesetChecksum:EVIDENCE_RULESET_CHECKSUM,metrics:null,warnings:[error.code||'SUPPLYGRAPH_EVIDENCE_UNAVAILABLE'],multiSupplierComparisonReady:false,basketOptimizationStatus:'not_implemented'};}}
}

module.exports={SupplierEvidenceService};
