import type { LucideIcon } from 'lucide-react';
import { Activity, Archive, BarChart3, Bot, Boxes, BriefcaseBusiness, CalendarDays, CheckCheck, ClipboardCheck, FileText, GitBranch, HeartHandshake, Image, LayoutDashboard, Library, ListChecks, Megaphone, MessageSquareText, PackageCheck, PackageSearch, Palette, PlugZap, Radio, ScanSearch, Settings, ShieldCheck, ShoppingBasket, Store, Tags, Users, WandSparkles, Workflow, Wrench } from 'lucide-react';

export type ModuleGroup = 'Command Center' | 'CornerMex Operations' | 'Seller Network' | 'Growth & Marketing' | 'Automation & Intelligence' | 'Governance & Safety' | 'Channels & Configuration';
export type ModuleKey = 'overview'|'control-tower'|'ai-chat'|'cornermex-ops'|'orders'|'products'|'b2b-leads'|'conversations'|'commercial-overview'|'commercial-accounts'|'commercial-opportunities'|'commercial-quotes'|'commercial-orders'|'commercial-payments'|'commercial-fulfillment'|'commercial-deliveries'|'commercial-exceptions'|'commercial-daily-close'|'authorized-sellers'|'seller-catalog'|'seller-inventory'|'seller-comparison'|'marketing'|'campaigns'|'content'|'brand'|'assets'|'promotions'|'audiences'|'calendar'|'analytics'|'flow-engine'|'intelligence'|'work-queue'|'drafts'|'worker-settings'|'product-activation'|'approvals'|'audit-log'|'security'|'capabilities'|'environment-doctor'|'telegram'|'integrations'|'settings';
export interface CommandCenterModule { key:ModuleKey;label:string;group:ModuleGroup;route:string;icon:LucideIcon;description:string;readOnly:boolean;requiredPermission:'public_read'|'operator_read'|'operator_controlled';blockedActions:string[];aliases?:string[];sortOrder:number }
const m=(key:ModuleKey,label:string,group:ModuleGroup,route:string,icon:LucideIcon,description:string,sortOrder:number,options:Partial<CommandCenterModule>={}):CommandCenterModule=>({key,label,group,route,icon,description,sortOrder,readOnly:true,requiredPermission:'operator_read',blockedActions:['production_writes','external_actions'],...options});
export const moduleRegistry:CommandCenterModule[]=[
  m('overview','Overview','Command Center','/overview',LayoutDashboard,'Live operational summary.',10,{aliases:['/']}),m('control-tower','Control Tower','Command Center','/control-tower',ShieldCheck,'Executive safety and readiness summary.',20),m('ai-chat','AI Chat Center','Command Center','/ai-chat',MessageSquareText,'Authenticated internal operator conversation.',30,{aliases:['/chat']}),
  m('cornermex-ops','CornerMex Ops','CornerMex Operations','/cornermex-ops',BriefcaseBusiness,'Read-only CornerMex operating status.',10),m('orders','Orders','CornerMex Operations','/orders',PackageSearch,'Read-only order records.',20),m('products','Products','CornerMex Operations','/products',Tags,'CornerMex active products, separate from seller listings.',30),m('b2b-leads','B2B Leads','CornerMex Operations','/b2b-leads',Users,'Read-only B2B opportunity records.',40,{aliases:['/leads']}),m('conversations','Conversations','CornerMex Operations','/conversations',Bot,'Persisted internal conversation history.',50),
  m('commercial-overview','Commercial Overview','CornerMex Operations','/commercial',BriefcaseBusiness,'Authorized internal commercial pipeline and daily priorities.',60),m('commercial-accounts','Accounts','CornerMex Operations','/commercial/accounts',Users,'Authorized B2B account coverage without contact PII.',70),m('commercial-opportunities','Opportunities','CornerMex Operations','/commercial/opportunities',GitBranch,'Commercial opportunities and next actions.',80),m('commercial-quotes','Quotes','CornerMex Operations','/commercial/quotes',FileText,'Internal quotes with pricing evidence and send controls.',90),m('commercial-orders','Commercial Orders','CornerMex Operations','/commercial/orders',PackageSearch,'Accepted quotes and internal order state.',100),m('commercial-payments','Payments','CornerMex Operations','/commercial/payments',ClipboardCheck,'Payment evidence only; no payment capture.',110),m('commercial-fulfillment','Fulfillment','CornerMex Operations','/commercial/fulfillment',Boxes,'Manual pick, pack and carrier handoff state.',120),m('commercial-deliveries','Deliveries','CornerMex Operations','/commercial/deliveries',PackageCheck,'Shipment and delivery outcomes.',130),m('commercial-exceptions','Exceptions','CornerMex Operations','/commercial/exceptions',ShieldCheck,'Commercial blockers requiring accountable resolution.',140),m('commercial-daily-close','Daily Close','CornerMex Operations','/commercial/daily-close',CalendarDays,'Daily separation of quotes, orders and collected cash.',150),
  m('authorized-sellers','Authorized Sellers','Seller Network','/authorized-sellers',Store,'Verified seller profiles and readiness.',10),m('seller-catalog','Seller Catalog','Seller Network','/seller-catalog',Library,'Verified seller catalog listings.',20),m('seller-inventory','Seller Inventory','Seller Network','/seller-inventory',PackageCheck,'Operational inventory provenance.',30),m('seller-comparison','Seller Comparison','Seller Network','/seller-comparison',GitBranch,'Deterministic comparison within verified scope.',40),
  m('marketing','Marketing Hub','Growth & Marketing','/marketing',Megaphone,'Read-only marketing readiness and internal evidence.',10),m('campaigns','Campaign Planner','Growth & Marketing','/marketing/campaigns',ClipboardCheck,'Internal campaign planning; publishing blocked.',20),m('content','Content Studio','Growth & Marketing','/marketing/content',FileText,'Internal drafts only; external sends blocked.',30),m('brand','Brand Studio','Growth & Marketing','/marketing/brand',Palette,'Brand guidance and verified assets.',40),m('assets','Asset Library','Growth & Marketing','/marketing/assets',Image,'Private managed seller media evidence.',50),m('promotions','Promotions','Growth & Marketing','/marketing/promotions',WandSparkles,'Promotion proposals; activation blocked.',60),m('audiences','Audience Segments','Growth & Marketing','/marketing/audiences',HeartHandshake,'Aggregated segments without raw PII.',70),m('calendar','Marketing Calendar','Growth & Marketing','/marketing/calendar',CalendarDays,'Internal schedule; no automatic publishing.',80),m('analytics','Performance Analytics','Growth & Marketing','/marketing/analytics',BarChart3,'Real metrics only; empty until connected.',90),
  m('flow-engine','Flow Engine','Automation & Intelligence','/flow-engine',Workflow,'Read-only operational flow analysis.',10),m('intelligence','Intelligence','Automation & Intelligence','/intelligence',ScanSearch,'Internal intelligence and evidence.',20),m('work-queue','Work Queue','Automation & Intelligence','/work-queue',ListChecks,'Persistent internal recommendations.',30),m('drafts','Drafts','Automation & Intelligence','/drafts',Archive,'Local drafts that are not externally sendable.',40),m('worker-settings','Worker Settings','Automation & Intelligence','/worker-settings',Wrench,'Worker configuration and safety posture.',50),
  m('product-activation','Product Activation','Governance & Safety','/product-activation',ShoppingBasket,'Activation remains blocked.',10),m('approvals','Approvals','Governance & Safety','/approvals',CheckCheck,'Human decisions; execution remains false.',20),m('audit-log','Audit Log','Governance & Safety','/audit-log',Activity,'Append-only sanitized evidence.',30),m('security','Security','Governance & Safety','/security',ShieldCheck,'Fail-closed security posture.',40),m('capabilities','Capability Status','Governance & Safety','/capabilities',ShieldCheck,'Truthful non-executing capability registry.',50),m('environment-doctor','Environment Doctor','Governance & Safety','/environment-doctor',Wrench,'Configuration readiness without secret values.',60),
  m('telegram','Telegram','Channels & Configuration','/telegram',Radio,'Founder allowlist and polling status.',10),m('integrations','Integrations','Channels & Configuration','/integrations',PlugZap,'Integration readiness and disabled channels.',20),m('settings','Settings','Channels & Configuration','/settings',Settings,'Unified workspace settings.',30),
];
export const moduleGroups:ModuleGroup[]=['Command Center','CornerMex Operations','Seller Network','Growth & Marketing','Automation & Intelligence','Governance & Safety','Channels & Configuration'];
export const modulesByGroup=moduleGroups.map(group=>({group,modules:moduleRegistry.filter(item=>item.group===group).sort((a,b)=>a.sortOrder-b.sortOrder)}));
export const moduleByKey=Object.fromEntries(moduleRegistry.map(item=>[item.key,item])) as Record<ModuleKey,CommandCenterModule>;
