const UNKNOWN_VALUES = Object.freeze(['unknown', 'not_provided', 'pending_verification']);

const OPPORTUNITY_STATES = Object.freeze([
  'NEW', 'QUALIFYING', 'CONTACT_READY', 'QUOTE_REQUIRED', 'QUOTE_IN_PROGRESS',
  'QUOTE_SENT_MANUALLY', 'NEGOTIATING', 'WON', 'LOST', 'ON_HOLD',
]);
const QUOTE_STATES = Object.freeze([
  'DRAFT_NOT_SENT', 'READY_FOR_REVIEW', 'APPROVED_INTERNAL', 'REJECTED_INTERNAL',
  'EXPORTED_FOR_MANUAL_SEND', 'SENT_MANUALLY_CONFIRMED', 'ACCEPTED', 'DECLINED', 'EXPIRED',
]);
const ORDER_STATES = Object.freeze([
  'ORDER_DRAFT', 'ORDER_CONFIRMED', 'PAYMENT_PENDING', 'PAYMENT_PARTIAL', 'PAID',
  'READY_FOR_FULFILLMENT', 'FULFILLING', 'SHIPPED', 'DELIVERED', 'CANCELLED',
  'REFUND_REQUIRED', 'ON_HOLD',
]);
const PAYMENT_METHODS = Object.freeze([
  'CARD_ONLINE', 'CASH_ON_DELIVERY', 'BANK_TRANSFER', 'MARKETPLACE', 'OTHER',
]);
const FULFILLMENT_STATES = Object.freeze([
  'WAITING_PAYMENT', 'READY_TO_PICK', 'PICKING', 'PACKED', 'HANDED_TO_CARRIER',
  'IN_TRANSIT', 'DELIVERED', 'DELIVERY_FAILED', 'RETURNED', 'BLOCKED',
]);
const EXCEPTION_TYPES = Object.freeze([
  'PRICE_MISSING', 'PRICE_UNAPPROVED', 'OUT_OF_STOCK', 'INVENTORY_UNKNOWN',
  'PAYMENT_OVERDUE', 'PAYMENT_MISMATCH', 'FULFILLMENT_DELAY', 'DELIVERY_FAILED',
  'CUSTOMER_RESPONSE_REQUIRED', 'REGISTRATION_BLOCKED', 'MARGIN_BELOW_GUARDRAIL',
  'DUPLICATE_ORDER', 'DATA_INCOMPLETE',
]);
const EXCEPTION_STATES = Object.freeze(['OPEN', 'ACKNOWLEDGED', 'IN_PROGRESS', 'RESOLVED', 'DISMISSED_WITH_REASON']);

const transitions = Object.freeze({
  quote: Object.freeze({
    DRAFT_NOT_SENT: ['READY_FOR_REVIEW'],
    READY_FOR_REVIEW: ['APPROVED_INTERNAL', 'REJECTED_INTERNAL', 'DRAFT_NOT_SENT'],
    APPROVED_INTERNAL: ['EXPORTED_FOR_MANUAL_SEND'],
    EXPORTED_FOR_MANUAL_SEND: ['SENT_MANUALLY_CONFIRMED'],
    SENT_MANUALLY_CONFIRMED: ['ACCEPTED', 'DECLINED', 'EXPIRED'],
  }),
  order: Object.freeze({
    ORDER_DRAFT: ['ORDER_CONFIRMED', 'CANCELLED'],
    ORDER_CONFIRMED: ['PAYMENT_PENDING', 'PAID', 'ON_HOLD', 'CANCELLED'],
    PAYMENT_PENDING: ['PAYMENT_PARTIAL', 'PAID', 'ON_HOLD', 'CANCELLED'],
    PAYMENT_PARTIAL: ['PAID', 'ON_HOLD', 'CANCELLED'],
    PAID: ['READY_FOR_FULFILLMENT', 'REFUND_REQUIRED', 'ON_HOLD'],
    READY_FOR_FULFILLMENT: ['FULFILLING', 'ON_HOLD'],
    FULFILLING: ['SHIPPED', 'ON_HOLD'],
    SHIPPED: ['DELIVERED', 'ON_HOLD'],
  }),
  fulfillment: Object.freeze({
    WAITING_PAYMENT: ['READY_TO_PICK', 'BLOCKED'],
    READY_TO_PICK: ['PICKING', 'BLOCKED'],
    PICKING: ['PACKED', 'BLOCKED'],
    PACKED: ['HANDED_TO_CARRIER', 'BLOCKED'],
    HANDED_TO_CARRIER: ['IN_TRANSIT', 'BLOCKED'],
    IN_TRANSIT: ['DELIVERED', 'DELIVERY_FAILED', 'RETURNED'],
    DELIVERY_FAILED: ['IN_TRANSIT', 'RETURNED', 'BLOCKED'],
  }),
});

const commercialError = (message, code, statusCode = 400, details) => {
  const error = new Error(message);
  error.code = code;
  error.statusCode = statusCode;
  if (details) error.details = details;
  return error;
};

module.exports = {
  EXCEPTION_STATES, EXCEPTION_TYPES, FULFILLMENT_STATES, OPPORTUNITY_STATES,
  ORDER_STATES, PAYMENT_METHODS, QUOTE_STATES, UNKNOWN_VALUES, commercialError, transitions,
};
