const UNKNOWN_VALUES = Object.freeze(['unknown', 'not_provided', 'pending_verification']);

const OPPORTUNITY_STATES = Object.freeze([
  'NEW', 'QUALIFYING', 'CONTACT_READY', 'QUOTE_REQUIRED', 'QUOTE_IN_PROGRESS',
  'QUOTE_SENT_MANUALLY', 'NEGOTIATING', 'WON', 'LOST', 'ON_HOLD',
]);
const QUOTE_STATES = Object.freeze([
  'DRAFT_NOT_SENT', 'READY_FOR_REVIEW', 'APPROVED_INTERNAL', 'REJECTED_INTERNAL',
  'EXPORTED_FOR_MANUAL_SEND', 'SENT_MANUALLY_CONFIRMED', 'ACCEPTED', 'DECLINED', 'EXPIRED',
]);
const ORDER_STATES = Object.freeze([
  'ORDER_DRAFT', 'ORDER_CONFIRMED', 'PAYMENT_PENDING', 'PAYMENT_PARTIAL', 'PAID',
  'READY_FOR_FULFILLMENT', 'FULFILLING', 'SHIPPED', 'DELIVERED', 'CANCELLED',
  'REFUND_REQUIRED', 'ON_HOLD',
]);
const PAYMENT_METHODS = Object.freeze([
  'CARD_ONLINE', 'CASH_ON_DELIVERY', 'BANK_TRANSFER', 'MARKETPLACE', 'OTHER',
]);
const BANK_TRANSFER_STATES = Object.freeze([
  'BANK_TRANSFER_PENDING_VERIFICATION', 'BANK_TRANSFER_SETTLEMENT_CONFIRMED',
  'BANK_TRANSFER_REJECTED', 'BANK_TRANSFER_DISCREPANCY',
]);
const COD_PAYMENT_STATES = Object.freeze([
  'COD_PENDING_COLLECTION', 'COD_COLLECTED_PENDING_REMITTANCE',
  'COD_REMITTANCE_PENDING_VERIFICATION', 'COD_REMITTED_CONFIRMED',
  'COD_DISCREPANCY', 'COD_REJECTED', 'COD_FAILED',
]);
const FULFILLMENT_STATES = Object.freeze([
  'WAITING_PAYMENT', 'READY_FOR_INTERMEX_HANDOFF', 'INTERMEX_HANDOFF_PENDING',
  'INTERMEX_HANDOFF_CONFIRMED', 'ACCEPTED_BY_INTERMEX',
  'READY_TO_PICK', 'PICKING', 'PACKED', 'HANDED_TO_CARRIER',
  'IN_TRANSIT', 'DELIVERED', 'DELIVERY_FAILED', 'RETURNED', 'BLOCKED',
]);
const EXTERNAL_FULFILLMENT_STATES = Object.freeze([
  'INTERMEX_HANDOFF_CONFIRMED', 'ACCEPTED_BY_INTERMEX', 'PICKING', 'PACKED',
  'HANDED_TO_CARRIER', 'IN_TRANSIT', 'DELIVERED', 'DELIVERY_FAILED', 'RETURNED',
]);
const INVENTORY_STATUSES = Object.freeze([
  'UNKNOWN', 'REPORTED', 'STALE', 'UNAVAILABLE', 'RESERVED',
  'CONFIRMATION_REQUIRED', 'RECONCILIATION_REQUIRED',
]);
const EXCEPTION_TYPES = Object.freeze([
  'PRICE_MISSING', 'PRICE_UNAPPROVED', 'OUT_OF_STOCK', 'INVENTORY_UNKNOWN',
  'PAYMENT_OVERDUE', 'PAYMENT_MISMATCH', 'FULFILLMENT_DELAY', 'DELIVERY_FAILED',
  'CUSTOMER_RESPONSE_REQUIRED', 'REGISTRATION_BLOCKED', 'MARGIN_BELOW_GUARDRAIL',
  'DUPLICATE_ORDER', 'DATA_INCOMPLETE', 'INVENTORY_NOT_CONFIRMED',
  'STALE_INVENTORY_EVIDENCE', 'QUANTITY_MISMATCH', 'DAMAGED_PRODUCT',
  'EXPIRED_PRODUCT', 'NEAR_EXPIRY_PRODUCT', 'SUBSTITUTED_PRODUCT',
  'PICKING_ERROR', 'PACKING_ERROR', 'INTERMEX_ORDER_REJECTED',
  'INTERMEX_HANDOFF_NOT_CONFIRMED', 'MISSING_TRACKING_REFERENCE',
  'COD_DISCREPANCY', 'CUSTOMER_CANCELLATION', 'PAYMENT_NOT_CONFIRMED',
]);
const EXCEPTION_STATES = Object.freeze(['OPEN', 'ACKNOWLEDGED', 'IN_PROGRESS', 'RESOLVED', 'DISMISSED_WITH_REASON']);
const EXCEPTION_SEVERITY_DEFAULTS = Object.freeze({
  INVENTORY_NOT_CONFIRMED: 'medium', STALE_INVENTORY_EVIDENCE: 'medium', QUANTITY_MISMATCH: 'high',
  DAMAGED_PRODUCT: 'high', EXPIRED_PRODUCT: 'critical', NEAR_EXPIRY_PRODUCT: 'high',
  SUBSTITUTED_PRODUCT: 'high', PICKING_ERROR: 'high', PACKING_ERROR: 'high',
  INTERMEX_ORDER_REJECTED: 'high', INTERMEX_HANDOFF_NOT_CONFIRMED: 'high',
  MISSING_TRACKING_REFERENCE: 'medium', COD_DISCREPANCY: 'critical',
  CUSTOMER_CANCELLATION: 'medium', PAYMENT_NOT_CONFIRMED: 'high', DELIVERY_FAILED: 'high',
});

const transitions = Object.freeze({
  quote: Object.freeze({
    DRAFT_NOT_SENT: ['READY_FOR_REVIEW'],
    READY_FOR_REVIEW: ['APPROVED_INTERNAL', 'REJECTED_INTERNAL', 'DRAFT_NOT_SENT'],
    APPROVED_INTERNAL: ['EXPORTED_FOR_MANUAL_SEND'],
    EXPORTED_FOR_MANUAL_SEND: ['SENT_MANUALLY_CONFIRMED'],
    SENT_MANUALLY_CONFIRMED: ['ACCEPTED', 'DECLINED', 'EXPIRED'],
  }),
  order: Object.freeze({
    ORDER_DRAFT: ['ORDER_CONFIRMED', 'CANCELLED'],
    ORDER_CONFIRMED: ['PAYMENT_PENDING', 'PAID', 'ON_HOLD', 'CANCELLED'],
    PAYMENT_PENDING: ['PAYMENT_PARTIAL', 'PAID', 'ON_HOLD', 'CANCELLED'],
    PAYMENT_PARTIAL: ['PAID', 'ON_HOLD', 'CANCELLED'],
    PAID: ['READY_FOR_FULFILLMENT', 'REFUND_REQUIRED', 'ON_HOLD'],
    READY_FOR_FULFILLMENT: ['FULFILLING', 'ON_HOLD'],
    FULFILLING: ['SHIPPED', 'ON_HOLD'],
    SHIPPED: ['DELIVERED', 'ON_HOLD'],
  }),
  paymentBank: Object.freeze({
    BANK_TRANSFER_PENDING_VERIFICATION: ['BANK_TRANSFER_SETTLEMENT_CONFIRMED', 'BANK_TRANSFER_REJECTED', 'BANK_TRANSFER_DISCREPANCY'],
    BANK_TRANSFER_DISCREPANCY: ['BANK_TRANSFER_SETTLEMENT_CONFIRMED', 'BANK_TRANSFER_REJECTED'],
  }),
  paymentCod: Object.freeze({
    COD_PENDING_COLLECTION: ['COD_COLLECTED_PENDING_REMITTANCE', 'COD_REJECTED', 'COD_FAILED'],
    COD_COLLECTED_PENDING_REMITTANCE: ['COD_REMITTANCE_PENDING_VERIFICATION', 'COD_DISCREPANCY', 'COD_FAILED'],
    COD_REMITTANCE_PENDING_VERIFICATION: ['COD_REMITTED_CONFIRMED', 'COD_DISCREPANCY', 'COD_REJECTED'],
    COD_DISCREPANCY: ['COD_REMITTANCE_PENDING_VERIFICATION', 'COD_REJECTED', 'COD_FAILED'],
  }),
  fulfillment: Object.freeze({
    WAITING_PAYMENT: ['READY_FOR_INTERMEX_HANDOFF', 'BLOCKED'],
    READY_FOR_INTERMEX_HANDOFF: ['INTERMEX_HANDOFF_PENDING', 'BLOCKED'],
    INTERMEX_HANDOFF_PENDING: ['INTERMEX_HANDOFF_CONFIRMED', 'BLOCKED'],
    INTERMEX_HANDOFF_CONFIRMED: ['ACCEPTED_BY_INTERMEX', 'BLOCKED'],
    ACCEPTED_BY_INTERMEX: ['READY_TO_PICK', 'BLOCKED'],
    READY_TO_PICK: ['PICKING', 'BLOCKED'],
    PICKING: ['PACKED', 'BLOCKED'],
    PACKED: ['HANDED_TO_CARRIER', 'BLOCKED'],
    HANDED_TO_CARRIER: ['IN_TRANSIT', 'BLOCKED'],
    IN_TRANSIT: ['DELIVERED', 'DELIVERY_FAILED', 'RETURNED'],
    DELIVERY_FAILED: ['IN_TRANSIT', 'RETURNED', 'BLOCKED'],
  }),
});

const commercialError = (message, code, statusCode = 400, details) => {
  const error = new Error(message);
  error.code = code;
  error.statusCode = statusCode;
  if (details) error.details = details;
  return error;
};

module.exports = {
  BANK_TRANSFER_STATES, COD_PAYMENT_STATES, EXCEPTION_SEVERITY_DEFAULTS, EXCEPTION_STATES, EXCEPTION_TYPES,
  EXTERNAL_FULFILLMENT_STATES, FULFILLMENT_STATES, INVENTORY_STATUSES,
  OPPORTUNITY_STATES, ORDER_STATES, PAYMENT_METHODS, QUOTE_STATES, UNKNOWN_VALUES,
  commercialError, transitions,
};
